openapi: 3.1.0
info:
  title: 动画镜头任务管理系统 API
  version: 0.1.0
  description: |
    本文件记录当前前端已开始对接的接口契约。实现状态见各 path 的 summary/description。
    - Implementation status: Partial implementation（前端已对接，后端待实现或对齐）。
servers:
  - url: "{baseUrl}{prefix}"
    variables:
      baseUrl:
        default: https://your-domain.example
        description: 生产/测试环境域名。不得在代码中硬编码。
      prefix:
        default: /api
        description: 反向代理下的 API 前缀。
paths:
  /auth/login:
    post:
      summary: 用户登录（Partial implementation）
      description: 前端以 Cookie 会话登录；失败返回原因。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: { type: string }
                password: { type: string }
              required: [username, password]
      responses:
        '204': { description: 登录成功，无内容返回 }
        '400': { description: 参数错误 }
        '401': { description: 认证失败 }

  /auth/logout:
    post:
      summary: 退出登录（Partial implementation）
      responses:
        '204': { description: 成功 }

  /me:
    get:
      summary: 获取当前用户信息（Partial implementation）
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: { type: integer }
                  username: { type: string }
                  nickname: { type: string, nullable: true }
                  role: { type: string, enum: [Admin, Director, Producer, Artist] }

  /sets:
    get:
      summary: 读取全局 sets.json（Partial implementation）
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  stages: { type: array, items: { type: string } }
                  statuses: { type: array, items: { type: string } }

  /projects:
    get:
      summary: 查询可见项目列表（Partial implementation）
      parameters:
        - in: query
          name: q
          schema: { type: string }
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: { type: integer }
                    name: { type: string }
                    description: { type: string, nullable: true }

  /projects/{projectId}/tasks:
    get:
      summary: 查询项目内任务（Partial implementation）
      parameters:
        - in: path
          name: projectId
          required: true
          schema: { type: integer }
        - in: query
          name: q
          schema: { type: string }
        - in: query
          name: stage
          schema: { type: string }
        - in: query
          name: status
          schema: { type: string }
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: { type: integer }
                    shotNo: { type: string }
                    title: { type: string }
                    stage: { type: string }
                    status: { type: string }
                    dueDate: { type: string, format: date-time, nullable: true }

  /tasks/{taskId}:
    get:
      summary: 获取任务详情（Partial implementation）
      parameters:
        - in: path
          name: taskId
          required: true
          schema: { type: integer }
      responses:
        '200': { description: 成功 }

  /tasks/{taskId}/versions:
    get:
      summary: 获取任务历史版本（Partial implementation）
      parameters:
        - in: path
          name: taskId
          required: true
          schema: { type: integer }
      responses:
        '200': { description: 成功 }

  /tasks/{taskId}/versions/{versionNo}/download:
    get:
      summary: 下载指定版本（Partial implementation）
      parameters:
        - in: path
          name: taskId
          required: true
          schema: { type: integer }
        - in: path
          name: versionNo
          required: true
          schema: { type: integer }
      responses:
        '200': { description: 文件流 }

  /tasks/{taskId}/comments:
    get:
      summary: 获取评论列表（Partial implementation）
      parameters:
        - in: path
          name: taskId
          required: true
          schema: { type: integer }
      responses:
        '200': { description: 成功 }
    post:
      summary: 新增评论（Partial implementation）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content: { type: string }
              required: [content]
      responses:
        '201': { description: 已创建 }

  /search:
    get:
      summary: 全局搜索（Partial implementation）
      parameters:
        - in: query
          name: q
          required: true
          schema: { type: string }
      responses:
        '200': { description: 成功 }


